---
- name: Load encrypted credentials
  community.sops.load_vars:
    file: ../../../../secrets.sops.yml

- name: Install Tailscale
  include_role:
    name: artis3n.tailscale
  vars:
    tailscale_authkey: "{{ tailscale_auth_key }}"
    tailscale_args: "--ssh"
